version: "3.7"
services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app:delegated
  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app:delegated
  db:
    image: mdillon/postgis
    hostname: db
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: wps
      POSTGRES_PASSWORD: wps
      POSTGRES_DATABASE: wps
    volumes:
      - /var/lib/postgresql